title: Georgia Jenkins # your name (or website title) here
subtitle: Data Scientist and MPH
logo: "/images/headshot_round.png?raw=true" # your photo (or logo) here
description: > 
  <br>
  <a href="https://www.linkedin.com/in/jenkins-georgia/" target="_blank">
    <i class="fab fa-linkedin fa-2x"></i>
  </a>
  <a href="https://github.com/geojenk" target="_blank">
    <i class="fab fa-github fa-2x"></i>
  </a>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
